#base   "../../../../cfg/hud-fixes/hud_float_damage.txt"
#base   "../../../../cfg/hud-fixes/hud_last_damage.txt"
#base	"../../_extras/resource/ui/huddamageaccount.res"
#base	"../../_fixes/resource/ui/huddamageaccount.res"
#base	"../../_tf2hud/resource/ui/huddamageaccount.res"