#pragma once
#include "shaderlib/cshader.h"
class shadowmodel_ps30_Static_Index
{
public:
	shadowmodel_ps30_Static_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_shadowmodel_ps30 1


class shadowmodel_ps30_Dynamic_Index
{
public:
	shadowmodel_ps30_Dynamic_Index(  )
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_shadowmodel_ps30 1

