name: Linux
on: 
  workflow_call:

env:
  CCACHE_VERSION: 4.0
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          # Use hashFiles so the cache updates when code changes, not just every day
          key: ${{ runner.os }}-ccache-${{ hashFiles('src/**/*.cpp', 'src/**/*.h') }}
          restore-keys: ${{ runner.os }}-ccache-

      - name: Configure Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip build-essential gcc-multilib g++-multilib podman ccache

      - name: Setup ccache
        run: |
          mkdir -p game/tf2vintage/bin
          ccache --set-config=cache_dir=${{ env.CCACHE_DIR }}
          ccache --set-config=max_size=2.0G

      - name: Build
        run: |
          cd src
          # Assuming your build script doesn't strictly require root
          bash createallprojects
          # Add your build commands here...

      - name: Upload product
        uses: actions/upload-artifact@v4
        with:
          name: tf2vintage-linux
          path: game/tf2vintage/bin/