name: Windows
on:
  workflow_call:
    inputs:
      build_config:
        description: 'MSBuild configuration — Release or Debug'
        type: string
        default: 'Release'

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Fix Python PATH
        run: |
          $pythonPath = (Get-Command python).Source | Split-Path
          echo "$pythonPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create project
        run: |
          cd src
          .\createtf2vintage.bat

      - name: Build project
        run: |
          cd src
          MSBuild.exe TF2vintage.sln /p:Configuration=${{ inputs.build_config }} /p:Platform="win64" /m /v:m

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: tf2vintage-windows
          path: |
            game/tf2vintage/bin/**/*.dll
            game/tf2vintage/bin/**/*.exe

      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: tf2vintage-windows-debugsymbols
          path: game/tf2vintage/bin/**/*.pdb
