name: Windows
on: 
  workflow_call:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create project
        run: |
          cd src
          .\devtools\bin\vpc.exe /tf2vintage /define:SOURCESDK /define:TF +game /mksln TF2vintage.sln

      - name: Build project
        run: |
          cd src
          devenv TF2vintage.sln /Build Release

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: tf2vintage-windows
          path: |
            game/tf2vintage/bin/**/*.dll
            game/tf2vintage/bin/**/*.exe

      - name: Upload debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: tf2vintage-windows-debugsymbols
          path: game/tf2vintage/bin/**/*.pdb
